"""create_initial_tables

Revision ID: 9d12543eca9e
Revises: 732e5a8288fc
Create Date: 2025-05-11 01:42:04.552779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Import your Enums from the models to ensure Alembic uses them correctly
# Adjust the import path if your alembic setup is different or if they are defined elsewhere
from src.models.database import ServerStatus, AlertSeverity


# revision identifiers, used by Alembic.
revision: str = '9d12543eca9e'
down_revision: Union[str, None] = '732e5a8288fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Define ENUM types for use in column definitions
    # Let op.create_table handle their creation
    server_status_enum = sa.Enum(ServerStatus, name='serverstatus')
    alert_severity_enum = sa.Enum(AlertSeverity, name='alertseverity')

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', server_status_enum, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_index(op.f('ix_servers_ip_address'), 'servers', ['ip_address'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('severity', alert_severity_enum, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('ram_usage', sa.Float(), nullable=False),
    sa.Column('disk_usage', sa.Float(), nullable=False),
    sa.Column('app_usage', sa.Float(), nullable=False),
    sa.Column('network_traffic', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_servers_ip_address'), table_name='servers')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_table('servers')

    # Drop enum types
    sa.Enum(AlertSeverity, name='alertseverity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(ServerStatus, name='serverstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
